# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  npm_config_cache: $(Pipeline.Workspace)/.npm

steps:
  - task: Cache@2
    inputs:
      key: "package-lock.json"
      path: $(npm_config_cache)
    displayName: Cache NPM packages
  - script: npm ci --cache $(npm_config_cache)
    workingDirectory: src/app
    displayName: "Install npm modules"

  - script: npm run build
    workingDirectory: src/app
    displayName: "Build sveltekit app"
