# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  npm_config_cache: $(Pipeline.Workspace)/.npm

stages:
  - stage: Build
    displayName: Build ui, api and cdk
    jobs:
      - job: Build
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "18.x"
            displayName: "Install NodeJS v18"
          - task: Cache@2
            inputs:
              key: "src/app/package-lock.json"
              path: $(npm_config_cache)
            displayName: Cache NPM packages
          - script: npm ci --cache $(npm_config_cache)
            workingDirectory: src/app
            displayName: "Install npm modules"

          - script: npm run build
            displayName: "Build UI"
            workingDirectory: src/app
            env:
              PUBLIC_API_URL: "***REPLACE_API_URL***"
              PUBLIC_BUILD: "***REPLACE_BUILD***"
              PUBLIC_COMMIT: "***REPLACE_COMMIT***"
              PUBLIC_DOTNET_VERSION: "***REPLACE_DOTNET_VERSION***"
              PUBLIC_SVELTEKIT_VERSION: "***REPLACE_SVELTKIT_VERSION***"
              PUBLIC_ENVIRONMENT: "***REPLACE_ENVIRONMENT***"
              PUBLIC_ENVIRONMENT_COLOR: "***REPLACE_ENVIRONMENT_COLOR***"

          # - publish: $(System.DefaultWorkingDirectory)/src/app/build
          #   artifact: UI

          - task: UseDotNet@2
            displayName: "Use .NET Core sdk"
            inputs:
              packageType: sdk
              version: 7.x
              installationPath: $(Agent.ToolsDirectory)/dotnet

          - script: dotnet publish --configuration "Release" /p:GenerateRuntimeConfigurationFiles=true --runtime linux-x64 --self-contained false --output ./build
            displayName: "Build .net api"
            workingDirectory: src/api/src/WebUI

          # - publish: $(System.DefaultWorkingDirectory)/src/api/build
          #   artifact: UI-Api

          - script: npm ci
            displayName: install npm modules for cdk
            workingDirectory: src/cdk

          - script: npm run cdk synth
            displayName: cdk synth
            workingDirectory: src/cdk
            env:
              CDK_ENVIRONMENT: "na"
              CDK_ENVIRONMENT_COLOR: "blue"
              CDK_DOMAIN: "garethduncan.dev"
              CDK_ABSOLUTE_DOMAIN: "development-blue.garethduncan.dev"
              CDK_HOSTED_ZONE_ID: "Z01595372U9MMWVFZ5I1W"
              CDK_CLOUD_FRONT_DOMAIN_CERTIFICATE_ARN: "arn:aws:acm:us-east-1:123456789012:certificate/d1b4be7d-be9c-47c9-8deb-abcb379c352b"
              CDK_APP_NAME: "garethduncandev"
              CDK_REMOVAL_POLICY: "destroy"
              CDK_ROBOTS_NO_INDEX: true
              CDK_DEFAULT_ACCOUNT: "123456789012"
              CDK_DEFAULT_REGION: "eu-west-2"
              CDK_API_TIMEOUT: "300"
              CDK_API_DEFAULTMEMORYALLOCATION: "256"
              CDK_API_CORS_ALLOWORIGINS: '["*"]'
              CDK_API_CORS_ALLOWHEADERS: '["*"]'
              CDK_API_IMAGE_ASSET_DIRECTORY: "../../api/build"
              CDK_UI_OUTPUT_DIRECTOR: "../../app/build"
              CDK_API_ASPNETCORE_ENVIRONMENT: "Development"
              CDK_API_ASPNETCORE_ENVIRONMENT_COLOR: "Blue"

            # CDK synth expects a stack name (an environment name) or all stacks
            # The problem with this, we want the builds to be environment agnostic so we can deploy
            # to any environment.
            # Two options
            # 1:  Have all environment names available in src so cdk synth can create a stack template for each environment
            #     - downside: potentially larger builds - not as flexible
            # 2:  Call cdk synth to check it works with a random environment name (that we may never use)
            #     Then on release, we call cdk deploy on src again
            #     - downside: technically rebuilding again on release, however the app and api builds will only be done once on build
            # Going with option 2

            # Delete cdk.out
            # publish src/cdk as artifact to run cdk deploy again
