//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

export interface IHelloClient {
	get(
		api_versionHeader?: string | null | undefined,
		api_versionQuery?: string | null | undefined
	): Promise<string>;
}

export class HelloClient implements IHelloClient {
	private http: {
		fetch(url: RequestInfo, init?: RequestInit): Promise<Response>;
	};
	private baseUrl: string;
	protected jsonParseReviver: ((key: string, value: any) => any) | undefined =
		undefined;

	constructor(
		baseUrl?: string,
		http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }
	) {
		this.http = http ? http : (window as any);
		this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : '';
	}

	get(
		api_versionHeader?: string | null | undefined,
		api_versionQuery?: string | null | undefined
	): Promise<string> {
		let url_ = this.baseUrl + '/?';
		if (api_versionQuery !== undefined && api_versionQuery !== null)
			url_ += 'api-version=' + encodeURIComponent('' + api_versionQuery) + '&';
		url_ = url_.replace(/[?&]$/, '');

		let options_: RequestInit = {
			method: 'GET',
			headers: {
				'api-version':
					api_versionHeader !== undefined && api_versionHeader !== null
						? '' + api_versionHeader
						: '',
				Accept: 'application/json; api-version=1'
			}
		};

		return this.http.fetch(url_, options_).then((_response: Response) => {
			return this.processGet(_response);
		});
	}

	protected processGet(response: Response): Promise<string> {
		const status = response.status;
		let _headers: any = {};
		if (response.headers && response.headers.forEach) {
			response.headers.forEach((v: any, k: any) => (_headers[k] = v));
		}
		if (status === 200) {
			return response.text().then((_responseText) => {
				let result200: any = null;
				let resultData200 =
					_responseText === ''
						? null
						: JSON.parse(_responseText, this.jsonParseReviver);
				result200 = resultData200 !== undefined ? resultData200 : <any>null;

				return result200;
			});
		} else if (status !== 200 && status !== 204) {
			return response.text().then((_responseText) => {
				return throwException(
					'An unexpected server error occurred.',
					status,
					_responseText,
					_headers
				);
			});
		}
		return Promise.resolve<string>(null as any);
	}
}

export interface IDiagnosticsClient {
	getDiagnostics(
		api_versionHeader?: string | null | undefined,
		api_versionQuery?: string | null | undefined
	): Promise<DiagnosticsVm>;
}

export class DiagnosticsClient implements IDiagnosticsClient {
	private http: {
		fetch(url: RequestInfo, init?: RequestInit): Promise<Response>;
	};
	private baseUrl: string;
	protected jsonParseReviver: ((key: string, value: any) => any) | undefined =
		undefined;

	constructor(
		baseUrl?: string,
		http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }
	) {
		this.http = http ? http : (window as any);
		this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : '';
	}

	getDiagnostics(
		api_versionHeader?: string | null | undefined,
		api_versionQuery?: string | null | undefined
	): Promise<DiagnosticsVm> {
		let url_ = this.baseUrl + '/diagnostics?';
		if (api_versionQuery !== undefined && api_versionQuery !== null)
			url_ += 'api-version=' + encodeURIComponent('' + api_versionQuery) + '&';
		url_ = url_.replace(/[?&]$/, '');

		let options_: RequestInit = {
			method: 'GET',
			headers: {
				'api-version':
					api_versionHeader !== undefined && api_versionHeader !== null
						? '' + api_versionHeader
						: '',
				Accept: 'application/json; api-version=1'
			}
		};

		return this.http.fetch(url_, options_).then((_response: Response) => {
			return this.processGetDiagnostics(_response);
		});
	}

	protected processGetDiagnostics(response: Response): Promise<DiagnosticsVm> {
		const status = response.status;
		let _headers: any = {};
		if (response.headers && response.headers.forEach) {
			response.headers.forEach((v: any, k: any) => (_headers[k] = v));
		}
		if (status === 200) {
			return response.text().then((_responseText) => {
				let result200: any = null;
				let resultData200 =
					_responseText === ''
						? null
						: JSON.parse(_responseText, this.jsonParseReviver);
				result200 = DiagnosticsVm.fromJS(resultData200);
				return result200;
			});
		} else if (status !== 200 && status !== 204) {
			return response.text().then((_responseText) => {
				return throwException(
					'An unexpected server error occurred.',
					status,
					_responseText,
					_headers
				);
			});
		}
		return Promise.resolve<DiagnosticsVm>(null as any);
	}
}

export class DiagnosticsVm implements IDiagnosticsVm {
	diagnostics!: DiagnosticsDto;

	constructor(data?: IDiagnosticsVm) {
		if (data) {
			for (var property in data) {
				if (data.hasOwnProperty(property))
					(<any>this)[property] = (<any>data)[property];
			}
		}
		if (!data) {
			this.diagnostics = new DiagnosticsDto();
		}
	}

	init(_data?: any) {
		if (_data) {
			this.diagnostics = _data['diagnostics']
				? DiagnosticsDto.fromJS(_data['diagnostics'])
				: new DiagnosticsDto();
		}
	}

	static fromJS(data: any): DiagnosticsVm {
		data = typeof data === 'object' ? data : {};
		let result = new DiagnosticsVm();
		result.init(data);
		return result;
	}

	toJSON(data?: any) {
		data = typeof data === 'object' ? data : {};
		data['diagnostics'] = this.diagnostics
			? this.diagnostics.toJSON()
			: <any>undefined;
		return data;
	}
}

export interface IDiagnosticsVm {
	diagnostics: DiagnosticsDto;
}

export class DiagnosticsDto implements IDiagnosticsDto {
	apiDateTime!: Date;
	environment!: string;
	environmentDisplayName!: string;

	constructor(data?: IDiagnosticsDto) {
		if (data) {
			for (var property in data) {
				if (data.hasOwnProperty(property))
					(<any>this)[property] = (<any>data)[property];
			}
		}
	}

	init(_data?: any) {
		if (_data) {
			this.apiDateTime = _data['apiDateTime']
				? new Date(_data['apiDateTime'].toString())
				: <any>undefined;
			this.environment = _data['environment'];
			this.environmentDisplayName = _data['environmentDisplayName'];
		}
	}

	static fromJS(data: any): DiagnosticsDto {
		data = typeof data === 'object' ? data : {};
		let result = new DiagnosticsDto();
		result.init(data);
		return result;
	}

	toJSON(data?: any) {
		data = typeof data === 'object' ? data : {};
		data['apiDateTime'] = this.apiDateTime
			? this.apiDateTime.toISOString()
			: <any>undefined;
		data['environment'] = this.environment;
		data['environmentDisplayName'] = this.environmentDisplayName;
		return data;
	}
}

export interface IDiagnosticsDto {
	apiDateTime: Date;
	environment: string;
	environmentDisplayName: string;
}

export class ApiException extends Error {
	override message: string;
	status: number;
	response: string;
	headers: { [key: string]: any };
	result: any;

	constructor(
		message: string,
		status: number,
		response: string,
		headers: { [key: string]: any },
		result: any
	) {
		super();

		this.message = message;
		this.status = status;
		this.response = response;
		this.headers = headers;
		this.result = result;
	}

	protected isApiException = true;

	static isApiException(obj: any): obj is ApiException {
		return obj.isApiException === true;
	}
}

function throwException(
	message: string,
	status: number,
	response: string,
	headers: { [key: string]: any },
	result?: any
): any {
	if (result !== null && result !== undefined) throw result;
	else throw new ApiException(message, status, response, headers, null);
}
